/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import classes.Book;
import classes.Book_loan;
import classes.*;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.ListIterator;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author abdul
 */

public class Borrower extends javax.swing.JFrame {

    /**
     * Creates new form Borrower
     */
    int row,col;
    int bk_id=-1;
    private Users_class obj;
    private ArrayList<Book> book_loans;
    private Book book_loan;
    public Borrower() {
        
        initComponents();
        
    }
    public Borrower(Users_class a) {
        
        initComponents();
        obj=a;
       t_name.setText(a.Name);
        t_username.setText(a.username);
        t_email.setText(a.Email);
        t_pno.setText(a.PhoneNumber);
        t_fine.setText(Integer.toString(a.computefine()));
        //Books.get(0).getbook();
         inittable();
        this.setVisible(true);
    }
    public void inittable()
    {
        ArrayList<Book_loan> Books=obj.getbooks();
        DefaultTableModel model = (DefaultTableModel) tl_books.getModel();
        DefaultComboBoxModel jcmodel = (DefaultComboBoxModel) jc_books.getModel();
            jcmodel.removeAllElements();
            
        model.setRowCount(0);
        model.setColumnCount(0);
        
        if(Books!=null)
        {
               int rows=Books.size();
         model.setRowCount(rows);
         model.addColumn("Sr No.");
         model.addColumn("Book");
         model.addColumn("Issue Data");
         model.addColumn("Expiry Date");
         model.addColumn("Fine");
         tl_books.setModel(model);
         ListIterator<Book_loan> iter=null;
         iter=Books.listIterator();
          int i=0;
         while (iter.hasNext()) {
             Book_loan temp=iter.next();
             String book=temp.getbook().getTitle()+" by "+temp.getbook().getAuthor()+" edition "+temp.getbook().getEdition();
             jcmodel.addElement(book);
             tl_books.setValueAt(Integer.toString(i+1),i,0);
             tl_books.setValueAt(book,i,1);
         tl_books.setValueAt(temp.getissue(),i,2);
         tl_books.setValueAt(temp.getret(),i,3);
         tl_books.setValueAt(temp.myfine(), i, 4);
         i++;
      }
        }
    }
    void refresh()
    {
        
        inittable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        kGradientPanel2 = new keeptoo.KGradientPanel();
        change_password = new keeptoo.KButton();
        c_password = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        n_password = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        nc_password = new javax.swing.JPasswordField();
        jDialog2 = new javax.swing.JDialog();
        kGradientPanel3 = new keeptoo.KGradientPanel();
        kButton2 = new keeptoo.KButton();
        l_label123 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        l_book = new javax.swing.JTextField();
        jDialog3 = new javax.swing.JDialog();
        kGradientPanel4 = new keeptoo.KGradientPanel();
        book_return = new keeptoo.KButton();
        jLabel11 = new javax.swing.JLabel();
        jc_books = new javax.swing.JComboBox<>();
        jDialog4 = new javax.swing.JDialog();
        kGradientPanel5 = new keeptoo.KGradientPanel();
        kButton4 = new keeptoo.KButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jDialog6 = new javax.swing.JDialog();
        kGradientPanel7 = new keeptoo.KGradientPanel();
        jc_book = new javax.swing.JComboBox<>();
        kButton5 = new keeptoo.KButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        j_extend = new javax.swing.JMenuItem();
        j_return = new javax.swing.JMenuItem();
        jDialog5 = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        tl_books = new javax.swing.JTable();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        t_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        t_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        t_pno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        t_username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        t_fine = new javax.swing.JTextField();
        change_password1 = new keeptoo.KButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jDialog1.setTitle("Password Change");
        jDialog1.setSize(new java.awt.Dimension(500, 500));

        kGradientPanel2.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel2.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel2.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        change_password.setText("Update Password");
        change_password.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        change_password.setkBorderRadius(40);
        change_password.setkEndColor(new java.awt.Color(102, 102, 255));
        change_password.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        change_password.setOpaque(false);
        change_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_passwordActionPerformed(evt);
            }
        });
        kGradientPanel2.add(change_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        c_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        c_password.setOpaque(false);
        c_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_passwordActionPerformed(evt);
            }
        });
        kGradientPanel2.add(c_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Current Password");
        kGradientPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 130, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(204, 204, 204));
        jLabel7.setText("New Password:");
        kGradientPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 120, 30));

        n_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        n_password.setOpaque(false);
        n_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                n_passwordActionPerformed(evt);
            }
        });
        kGradientPanel2.add(n_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 210, 30));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Confirm Password");
        kGradientPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 30));

        nc_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        nc_password.setOpaque(false);
        nc_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nc_passwordActionPerformed(evt);
            }
        });
        kGradientPanel2.add(nc_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 210, 30));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 957, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        jDialog2.setSize(new java.awt.Dimension(500, 500));

        kGradientPanel3.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel3.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel3.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton2.setText("Add Book");
        kButton2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        kButton2.setkBorderRadius(40);
        kButton2.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton2.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton2.setOpaque(false);
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(kButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        l_label123.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        l_label123.setForeground(new java.awt.Color(204, 204, 204));
        l_label123.setText("Select Book");
        kGradientPanel3.add(l_label123, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, 160, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/Capture.PNG"))); // NOI18N
        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        kGradientPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 80, 60));

        l_book.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        l_book.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        l_book.setOpaque(false);
        l_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                l_bookActionPerformed(evt);
            }
        });
        kGradientPanel3.add(l_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 220, 30));

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialog3.setSize(new java.awt.Dimension(500, 500));

        kGradientPanel4.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel4.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel4.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        book_return.setText("Return");
        book_return.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        book_return.setkBorderRadius(40);
        book_return.setkEndColor(new java.awt.Color(102, 102, 255));
        book_return.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        book_return.setOpaque(false);
        book_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                book_returnActionPerformed(evt);
            }
        });
        kGradientPanel4.add(book_return, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Select Book");
        kGradientPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 40));

        jc_books.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jc_books.setOpaque(false);
        kGradientPanel4.add(jc_books, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 180, -1));

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialog4.setSize(new java.awt.Dimension(500, 500));

        kGradientPanel5.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel5.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel5.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kButton4.setText("Extend Duration");
        kButton4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        kButton4.setkBorderRadius(40);
        kButton4.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton4.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton4.setOpaque(false);
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });
        kGradientPanel5.add(kButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, -1, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Select Book");
        kGradientPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 160, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.setOpaque(false);
        kGradientPanel5.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 180, -1));

        javax.swing.GroupLayout jDialog4Layout = new javax.swing.GroupLayout(jDialog4.getContentPane());
        jDialog4.getContentPane().setLayout(jDialog4Layout);
        jDialog4Layout.setHorizontalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog4Layout.createSequentialGroup()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog4Layout.setVerticalGroup(
            jDialog4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDialog6.setSize(new java.awt.Dimension(500, 500));

        kGradientPanel7.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel7.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jc_book.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nothing Found" }));
        jc_book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_bookActionPerformed(evt);
            }
        });
        kGradientPanel7.add(jc_book, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 170, 400, 30));

        kButton5.setText("Select book");
        kButton5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        kButton5.setkBorderRadius(40);
        kButton5.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton5.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton5.setOpaque(false);
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(kButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, -1, -1));

        javax.swing.GroupLayout jDialog6Layout = new javax.swing.GroupLayout(jDialog6.getContentPane());
        jDialog6.getContentPane().setLayout(jDialog6Layout);
        jDialog6Layout.setHorizontalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog6Layout.createSequentialGroup()
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 765, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDialog6Layout.setVerticalGroup(
            jDialog6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(kGradientPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPopupMenu1.setPreferredSize(new java.awt.Dimension(250, 50));

        j_extend.setText("jMenuItem8");
        jPopupMenu1.add(j_extend);

        j_return.setText("jMenuItem7");
        j_return.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                j_returnActionPerformed(evt);
            }
        });
        jPopupMenu1.add(j_return);

        jDialog5.setSize(new java.awt.Dimension(500, 500));

        tl_books.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tl_books.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                tl_booksMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tl_books);

        javax.swing.GroupLayout jDialog5Layout = new javax.swing.GroupLayout(jDialog5.getContentPane());
        jDialog5.getContentPane().setLayout(jDialog5Layout);
        jDialog5Layout.setHorizontalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 706, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );
        jDialog5Layout.setVerticalGroup(
            jDialog5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog5Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setkEndColor(new java.awt.Color(204, 255, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/149071_3ObHrl.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        t_name.setEditable(false);
        t_name.setBackground(new java.awt.Color(255, 255, 255));
        t_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        t_name.setOpaque(false);
        t_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_nameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, 210, 39));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setText("Name");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 70, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setText("Email");
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 70, 30));

        t_email.setEditable(false);
        t_email.setBackground(new java.awt.Color(255, 255, 255));
        t_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        t_email.setOpaque(false);
        t_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_emailActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 210, 39));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel4.setText("Phone No.");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 70, 30));

        t_pno.setEditable(false);
        t_pno.setBackground(new java.awt.Color(255, 255, 255));
        t_pno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_pno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        t_pno.setOpaque(false);
        t_pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_pnoActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, 210, 39));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel5.setText("Roll No.");
        kGradientPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, 70, 30));

        t_username.setEditable(false);
        t_username.setBackground(new java.awt.Color(255, 255, 255));
        t_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        t_username.setOpaque(false);
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 480, 210, 39));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel9.setText("Fine");
        kGradientPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 150, 80));

        t_fine.setEditable(false);
        t_fine.setBackground(new java.awt.Color(255, 255, 255));
        t_fine.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        t_fine.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(0, 0, 0)));
        t_fine.setOpaque(false);
        t_fine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_fineActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_fine, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 210, 39));

        change_password1.setText("See Details");
        change_password1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        change_password1.setkBorderRadius(40);
        change_password1.setkEndColor(new java.awt.Color(102, 102, 255));
        change_password1.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        change_password1.setOpaque(false);
        change_password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_password1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(change_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, -1, -1));

        jMenu1.setText("File");

        jMenuItem1.setText("Issue New Book");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Issued Book");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenuItem3.setText("Extend Book Duration");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Return a Book");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Change Password");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1070, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_nameActionPerformed

    private void t_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_emailActionPerformed

    private void t_pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_pnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_pnoActionPerformed

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        if(obj.computefine()>500)
        {
            JOptionPane.showMessageDialog(null, "Can not issue new book First clear your fine");
        }
        else
        jDialog2.setVisible(true);
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         jDialog4.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void change_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_passwordActionPerformed
        char[] pass;
        pass = c_password.getPassword();
        String c_Pass=new String(pass);
        
        if(obj.validate(obj.username,c_Pass))
        {
            pass = n_password.getPassword();
         c_Pass=new String(pass);
         pass = nc_password.getPassword();
        String nc_Pass=new String(pass);
        if( c_Pass.equals(nc_Pass))
        {
            obj.setPassword(c_Pass);
            JOptionPane.showMessageDialog(null, "Password changed");
            jDialog1.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Passwords dont match");
        }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Incorrect Password!");
        }
    }//GEN-LAST:event_change_passwordActionPerformed

    private void c_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_passwordActionPerformed

    private void n_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_n_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_n_passwordActionPerformed

    private void nc_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nc_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nc_passwordActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        jDialog1.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        // TODO add your handling code here:
        String book=l_label123.getText();
        l_book.setText("");
        l_book.setEditable(true);
        if(book_loan!=null)
        {
            if(obj.searchreqbook(book_loan)==false && obj.searchbook(book_loan)==false)
            {
        obj.reqBook(book_loan);
        JOptionPane.showMessageDialog(null, "Added");
        jDialog2.setVisible(false);
        }
            else
            {
                if(obj.searchbook(book_loan))
                {
                    JOptionPane.showMessageDialog(null, "You already have a copy of this book. System does not allow two copies");
                }
                else
                {
                JOptionPane.showMessageDialog(null, "Book already requested");
                }
                jDialog2.setVisible(false);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "No book found");
        }
        refresh();
        
    }//GEN-LAST:event_kButton2ActionPerformed

    private void book_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_book_returnActionPerformed
        // TODO add your handling code here:
        int book=jc_books.getSelectedIndex();
        String a=tl_books.getValueAt(book, 4).toString();
        int aa=Integer.parseInt(a);
        
        
        if(obj.searchretbook(book)==false)
        {
        Book temp=obj.Books.get(book).getbook();
         obj.retBook(temp);
         
        if(aa==0)
        JOptionPane.showMessageDialog(null, "Return Requested");
         else
              JOptionPane.showMessageDialog(null, "Fine paid and Return Requested");
        jDialog3.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Already Return Requested"); 
        }
    }//GEN-LAST:event_book_returnActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
         jDialog5.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void l_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_l_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_l_bookActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:
        String book=jc_book.getSelectedItem().toString();
        int index=jc_book.getSelectedIndex();
        if(book_loans.isEmpty()==false)
        book_loan=book_loans.get(index);
        if(book.equals("Nothing Found"))
        {
            
        }
        else
        {
                
         l_book.setText(book);
        
         l_book.setEditable(false);
        }
        jDialog6.setVisible(false);
        
    }//GEN-LAST:event_kButton5ActionPerformed

    private void jc_bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_bookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_bookActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String search=l_book.getText();
        book_loans=obj.Search(search);
        if(book_loans.isEmpty()==false)
        {
            jDialog6.setVisible(true);
            DefaultComboBoxModel model = (DefaultComboBoxModel) jc_book.getModel();
            model.removeAllElements();
            ListIterator<Book> it=null;
            it=book_loans.listIterator();
            while(it.hasNext())
            {
                Book temp=it.next();
                model.addElement(temp.getTitle()+" by "+temp.getAuthor()+"edition "+temp.getEdition());
                
            }
            
            
        }
        else
        {
            jDialog6.setVisible(true);
            DefaultComboBoxModel model = (DefaultComboBoxModel) jc_book.getModel();
            model.removeAllElements();
            model.addElement("Nothing Found");
            l_book.setEditable(true);
            kButton5.setText("Close");        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void t_fineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_fineActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_fineActionPerformed

    private void change_password1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_password1ActionPerformed
        // TODO add your handling code here:
        jDialog5.setVisible(true);
    }//GEN-LAST:event_change_password1ActionPerformed

    private void j_returnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_j_returnActionPerformed
        // TODO add your handling code here:
        String a=tl_books.getValueAt(row, 4).toString();
        int aa=Integer.parseInt(a);
        if(obj.searchretbook(row)==false)
        {
        Book temp=obj.Books.get(row).getbook();
         obj.retBook(temp);
         if(aa==0)
        JOptionPane.showMessageDialog(null, "Return Requested");
         else
              JOptionPane.showMessageDialog(null, "Fine paid and Return Requested");
        jDialog3.setVisible(false);
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Already Return Requested"); 
        }
        refresh();
    }//GEN-LAST:event_j_returnActionPerformed

    private void tl_booksMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tl_booksMouseReleased
        // TODO add your handling code here:
        if(evt.isPopupTrigger())
        {

            jPopupMenu1.show(tl_books, evt.getX(), evt.getY());
            row = tl_books.rowAtPoint(evt.getPoint());
            col = tl_books.columnAtPoint(evt.getPoint());
            String a=tl_books.getValueAt(row, 4).toString();
            int aa=Integer.parseInt(a);
            if(aa==0)
            {
                j_return.setText("Return Book");
                j_extend.setText("Extend Date");
            }
            else
            {
                j_return.setText("Return Book And Pay fine");
                j_extend.setText("Extend Date");
            }

        }
    }//GEN-LAST:event_tl_booksMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
       
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Borrower.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton book_return;
    private javax.swing.JPasswordField c_password;
    private keeptoo.KButton change_password;
    private keeptoo.KButton change_password1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JDialog jDialog4;
    private javax.swing.JDialog jDialog5;
    private javax.swing.JDialog jDialog6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem j_extend;
    private javax.swing.JMenuItem j_return;
    private javax.swing.JComboBox<String> jc_book;
    private javax.swing.JComboBox<String> jc_books;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private keeptoo.KGradientPanel kGradientPanel2;
    private keeptoo.KGradientPanel kGradientPanel3;
    private keeptoo.KGradientPanel kGradientPanel4;
    private keeptoo.KGradientPanel kGradientPanel5;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JTextField l_book;
    private javax.swing.JLabel l_label123;
    private javax.swing.JPasswordField n_password;
    private javax.swing.JPasswordField nc_password;
    private javax.swing.JTextField t_email;
    private javax.swing.JTextField t_fine;
    private javax.swing.JTextField t_name;
    private javax.swing.JTextField t_pno;
    private javax.swing.JTextField t_username;
    private javax.swing.JTable tl_books;
    // End of variables declaration//GEN-END:variables
}
