/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;

import classes.register_class;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author abdul
 */
public class registers extends javax.swing.JFrame {

    private register_class obj;
    /**
     * Creates new form registers
     */
    public registers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel7 = new keeptoo.KGradientPanel();
        jLabel16 = new javax.swing.JLabel();
        et_email = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        et_name = new javax.swing.JTextField();
        et_pno = new javax.swing.JTextField();
        et_username = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        kButton6 = new keeptoo.KButton();
        jLabel19 = new javax.swing.JLabel();
        t_password = new javax.swing.JPasswordField();
        jLabel21 = new javax.swing.JLabel();
        t_password1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel7.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel7.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel7.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel7.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Name");
        kGradientPanel7.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 70, 30));

        et_email.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        et_email.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        et_email.setOpaque(false);
        et_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_emailActionPerformed(evt);
            }
        });
        kGradientPanel7.add(et_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 210, 39));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Email");
        kGradientPanel7.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 70, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Phone No.");
        kGradientPanel7.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 70, 30));

        et_name.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        et_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        et_name.setOpaque(false);
        et_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_nameActionPerformed(evt);
            }
        });
        kGradientPanel7.add(et_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 210, 39));

        et_pno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        et_pno.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        et_pno.setOpaque(false);
        et_pno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_pnoActionPerformed(evt);
            }
        });
        kGradientPanel7.add(et_pno, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 210, 39));

        et_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        et_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        et_username.setOpaque(false);
        et_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_usernameActionPerformed(evt);
            }
        });
        kGradientPanel7.add(et_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 210, 39));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Password");
        kGradientPanel7.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 70, 30));

        kButton6.setText("Apply !");
        kButton6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        kButton6.setkBorderRadius(40);
        kButton6.setkEndColor(new java.awt.Color(102, 102, 255));
        kButton6.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        kButton6.setOpaque(false);
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });
        kGradientPanel7.add(kButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 710, -1, -1));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("User Name");
        kGradientPanel7.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 70, 30));

        t_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        t_password.setOpaque(false);
        kGradientPanel7.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 210, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Confirm Password");
        kGradientPanel7.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 590, 110, 30));

        t_password1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        t_password1.setOpaque(false);
        kGradientPanel7.add(t_password1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 640, 210, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 1051, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, 980, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void et_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_emailActionPerformed

    private void et_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_nameActionPerformed

    private void et_pnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_pnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_pnoActionPerformed

    private void et_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_usernameActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
        String name=et_name.getText();
        String email=et_email.getText();
        String pno=et_pno.getText();
        String username=et_username.getText();
        char[] pass;
        pass = t_password.getPassword();
        String Password=new String(pass);
        pass = t_password1.getPassword();
        String cpass=new String(pass);

        if(name.isEmpty() || email.isEmpty() || pno.isEmpty() || Password.isEmpty() || username.isEmpty() || cpass.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "All feilds are required");
        }
        else if(Password.equals(cpass))
        {
            obj=new register_class(username,cpass,pno,email,name);

            try {
                if(obj.checkusernameavil(username))
                {
                    JOptionPane.showMessageDialog(null, "Username not available");
                }
                else
                {
                                        
                    obj.addtodb();
                    JOptionPane.showMessageDialog(null, "Successfully applied");
                    this.setVisible(false);
                }
            } catch (SQLException ex) {
                Logger.getLogger(registers.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Passwords dont match");
        }
    }//GEN-LAST:event_kButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField et_email;
    private javax.swing.JTextField et_name;
    private javax.swing.JTextField et_pno;
    private javax.swing.JTextField et_username;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private keeptoo.KButton kButton6;
    private keeptoo.KGradientPanel kGradientPanel7;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JPasswordField t_password1;
    // End of variables declaration//GEN-END:variables
}
