/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication3;
import classes.driver;
import javax.swing.JOptionPane;
import classes.sign_in;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author abdul
 */
public class signin extends javax.swing.JFrame {

    /**
     * Creates new form signin
     */
    public Boolean done=false;
    public Boolean wrong=false;
    public Boolean exit=false;
    public String Username;
    public String Password;
    driver obj;
    public signin() {
        obj = null;
            try {
                obj = new driver();
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, ex);;
            }
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        b_signin = new keeptoo.KButton();
        t_username = new javax.swing.JTextField();
        t_password = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        c_accountType = new javax.swing.JComboBox<>();
        b_signin1 = new keeptoo.KButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1024, 768));

        kGradientPanel1.setBackground(new java.awt.Color(255, 255, 255));
        kGradientPanel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        kGradientPanel1.setkEndColor(new java.awt.Color(204, 0, 204));
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 102, 102));
        kGradientPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        b_signin.setText("Sign in");
        b_signin.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        b_signin.setkBorderRadius(40);
        b_signin.setkEndColor(new java.awt.Color(102, 102, 255));
        b_signin.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        b_signin.setOpaque(false);
        b_signin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_signinActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b_signin, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 350, -1, -1));

        t_username.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        t_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        t_username.setOpaque(false);
        t_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t_usernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(t_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 220, 30));

        t_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        t_password.setOpaque(false);
        kGradientPanel1.add(t_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 210, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("User Name:");
        kGradientPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 70, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Password:");
        kGradientPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 60, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication3/149071_3ObHrl.jpg"))); // NOI18N
        kGradientPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 220, 220));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("LMS");
        kGradientPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 210, 50));

        c_accountType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Please Select One Option--", "Student/Borrower", "Clerk", "Librarian" }));
        c_accountType.setOpaque(false);
        c_accountType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c_accountTypeActionPerformed(evt);
            }
        });
        kGradientPanel1.add(c_accountType, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 280, 210, 40));

        b_signin1.setText("New? Apply Now!");
        b_signin1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        b_signin1.setkBorderRadius(40);
        b_signin1.setkEndColor(new java.awt.Color(102, 102, 255));
        b_signin1.setkHoverStartColor(new java.awt.Color(51, 51, 51));
        b_signin1.setOpaque(false);
        b_signin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_signin1ActionPerformed(evt);
            }
        });
        kGradientPanel1.add(b_signin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t_usernameActionPerformed

    private void b_signinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_signinActionPerformed
        int a=c_accountType.getSelectedIndex();
        Username=t_username.getText();
        char[] pass;
        pass = t_password.getPassword();
        Password=new String(pass);
        
        
        if(a==0)
        {
            JOptionPane.showMessageDialog(null, "Please select one account type!!");
        }
        else if(Username.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Username!!");
        }
        else if(Password.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Please Enter Password!!");
        }
        else
        {
            
            if(obj.signin(Username, Password, a))
            {
                obj.signmein();
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Incorrect username or password");
            }
            
        }
        
        
        
        
    }//GEN-LAST:event_b_signinActionPerformed

    private void c_accountTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c_accountTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c_accountTypeActionPerformed

    private void b_signin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_signin1ActionPerformed
        // TODO add your handling code here:
        registers a=new registers();
        a.setVisible(true);
    }//GEN-LAST:event_b_signin1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        showsignin();
        
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(signin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }
    public static void showsignin()
    {
        signin a=new signin(); 
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton b_signin;
    private keeptoo.KButton b_signin1;
    private javax.swing.JComboBox<String> c_accountType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField t_password;
    private javax.swing.JTextField t_username;
    // End of variables declaration//GEN-END:variables
}
